version: '3'

networks:
  lisa:
    driver: bridge

services:
  databse:
    image: mongo
    networks:
      - lisa
    environment:
      MONGOLAB_URI: ${DATABASE_URI:-}
    ports:
      - "27017:27017"
  
  app:
    image: node:16.14.0
    volumes:
      - '.:/backend/'
    working_dir: /backend/
    depends_on:
      - databse
    networks:
      - lisa
    env_file:
      - .env
    ports:
      - 3333:3333
    command: yarn start